name       : dbus-glib
version    : '0.110'
release    : 12
source     :
    - https://dbus.freedesktop.org/releases/dbus-glib/dbus-glib-0.110.tar.gz : 7ce4760cf66c69148f6bd6c92feaabb8812dee30846b24cd0f7395c436d7e825
license    :
    - LGPL-2.0-or-later
summary    : D-Bus GLib Bindings
component  : system.base
builddeps  :
    - pkgconfig32(expat)
    - pkgconfig32(dbus-1)
    - pkgconfig32(gio-2.0)
    - pkgconfig32(liblzma)
    - libgcrypt-32bit-devel
emul32     : yes
description: |
    The D-Bus Bindings are a group of packages that contain programming language and platform interfaces to the D-Bus API. This is useful for programmers to easily interface D-Bus with their supported platform or language of choice. Some non-D-Bus packages will require one or more of the Bindings packages in order to build successfully.
setup      : |
    %configure --libexecdir=%libdir%/dbus-1.0 \
               --with-console-auth-dir=/run/console/ \
               --with-systemdsystemunitdir=%libdir%/systemd/system \
               --disable-static
build      : |
    %make
install    : |
    %make_install
