name       : dbus-glib
version    : '0.106'
release    : 9
source     :
    - https://dbus.freedesktop.org/releases/dbus-glib/dbus-glib-0.106.tar.gz : b38952706dcf68bad9c302999ef0f420b8cf1a2428227123f0ac4764b689c046
license    :
    - LGPL-2.0
summary    : D-Bus GLib Bindings
builddeps  :
    - pkgconfig32(expat)
    - pkgconfig32(dbus-1)
    - pkgconfig32(gio-2.0)
    - dbus-32bit
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    The D-Bus Bindings are a group of packages that contain programming language and platform interfaces to the D-Bus API. This is useful for programmers to easily interface D-Bus with their supported platform or language of choice. Some non-D-Bus packages will require one or more of the Bindings packages in order to build successfully.
setup      : |
    %configure --prefix=/usr \
               --localstatedir=/var \
               --libexecdir=%libdir%/dbus-1.0 \
               --with-console-auth-dir=/run/console/ \
               --with-systemdsystemunitdir=%libdir%/systemd/system \
               --disable-static
build      : |
    %make
install    : |
    %make_install
