name       : dbus-glib
version    : '0.112'
release    : 15
source     :
    - https://dbus.freedesktop.org/releases/dbus-glib/dbus-glib-0.112.tar.gz : 7d550dccdfcd286e33895501829ed971eeb65c614e73aadb4a08aeef719b143a
license    : LGPL-2.0-or-later
component  : system.base
summary    : D-Bus GLib Bindings
description: |
    The D-Bus Bindings are a group of packages that contain programming language and platform interfaces to the D-Bus API. This is useful for programmers to easily interface D-Bus with their supported platform or language of choice. Some non-D-Bus packages will require one or more of the Bindings packages in order to build successfully.
emul32     : yes
builddeps  :
    - pkgconfig32(expat)
    - pkgconfig32(dbus-1)
    - pkgconfig32(gio-2.0)
    - pkgconfig32(liblzma)
    - gtk-doc
    - libgcrypt-32bit-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Tweak-bash-completion-install-path.patch
    %reconfigure --libexecdir=%libdir%/dbus-1.0 \
               --with-console-auth-dir=/run/console/ \
               --with-systemdsystemunitdir=%libdir%/systemd/system \
               --disable-static
build      : |
    %make
install    : |
    %make_install
